### ISSUE TITLE
HU03 Consultar el listado de artistas : Añadir Pruebas End - to - End

### ISSUE THREAD

**Issue by jaPardor1** [robertoamin/Aplicacion_movil_vinilos#37]
Creación de las pruebas de extremo a extremo para asegurar que los componentes desarrollados funcionan bien en conjunto con los demás componentes del sistema.

**Comment by robertoamin** [comment]
Las pruebas se diseñaron y se ejecutaron de forma manual para lo que se adjunta video en el documento de estrategia de pruebas
